from setuptools import setup

setup(name="pychats",
      version="2.0.0",
      description="Conversation analytics",
      long_description="Tools for accessing conversation backups from various sources, and analysing said conversations.",
      url="pychats.samireland.com",
      author="Sam Ireland",
      author_email="mail@samireland.com",
      classifiers=["Development Status :: 4 - Beta",
                   "Intended Audience :: Other Audience",
                   "License :: OSI Approved :: MIT License",
                   "Topic :: Communications",
                   "Programming Language :: Python :: 3",
                   "Programming Language :: Python :: 3.0",
                   "Programming Language :: Python :: 3.1",
                   "Programming Language :: Python :: 3.2",
                   "Programming Language :: Python :: 3.3",
                   "Programming Language :: Python :: 3.4",
                   "Programming Language :: Python :: 3.5",
                   "Programming Language :: Python :: 3.6"],
      packages=["pychats", "pychats.chats"],
      install_requires=[])
